# -*- coding: utf-8 -*-
"""
配置系统自动生成器产出的配置类文件
该文件由 module/config/config_updater.py 自动生成，请勿手动修改！
功能说明：
1. 存储碧蓝航线自动化脚本（如Alas）的所有核心配置项
2. 包含资源管理、模拟器设置、任务调度、战斗配置、商店兑换等全维度配置
3. 所有配置项均为类属性，可直接通过类名访问，支持版本迁移和国际化适配
"""
import datetime

# 自动生成标记，提示用户不要手动修改
# This file was automatically generated by module/config/config_updater.py.
# Don't modify it manually.


class GeneratedConfig:
    """
    自动生成的碧蓝航线配置类
    包含游戏内所有可自动化配置项，按功能模块分组管理
    每个配置组以统一前缀命名（如Oil_xxx、Emulator_xxx），便于分类管理和检索
    """

    # ===================== 基础资源配置组 =====================
    # 石油配置 - 游戏内核心消耗资源
    Oil_Value = 0  # 当前石油数量
    Oil_Limit = 0  # 石油消耗上限（低于该值停止消耗石油的任务）
    Oil_Color = '^000000'  # 石油数值显示颜色（游戏内文本颜色码）
    Oil_Record = datetime.datetime(2020, 1, 1, 0, 0)  # 石油数值最后更新时间

    # 金币配置 - 游戏内基础货币
    Coin_Value = 0  # 当前金币数量
    Coin_Limit = 0  # 金币消耗上限
    Coin_Color = '^FFAA33'  # 金币数值显示颜色码
    Coin_Record = datetime.datetime(2020, 1, 1, 0, 0)  # 金币最后更新时间

    # 钻石配置 - 付费货币/核心稀缺资源
    Gem_Value = 0  # 当前钻石数量
    Gem_Color = '^FF3333'  # 钻石数值显示颜色码
    Gem_Record = datetime.datetime(2020, 1, 1, 0, 0)  # 钻石最后更新时间

    # PT点数配置 - 活动专用点数
    Pt_Value = 0  # 当前PT点数
    Pt_Color = '^00BFFF'  # PT数值显示颜色码
    Pt_Record = datetime.datetime(2020, 1, 1, 0, 0)  # PT点数最后更新时间

    # 黄币配置 - 商店兑换货币
    YellowCoin_Value = 0  # 当前黄币数量
    YellowCoin_Color = '^FF8800'  # 黄币数值显示颜色码
    YellowCoin_Record = datetime.datetime(2020, 1, 1, 0, 0)  # 黄币最后更新时间

    # 紫币配置 - 科研/活动兑换货币
    PurpleCoin_Value = 0  # 当前紫币数量
    PurpleCoin_Color = '^7700BB'  # 紫币数值显示颜色码
    PurpleCoin_Record = datetime.datetime(2020, 1, 1, 0, 0)  # 紫币最后更新时间

    # 行动力配置 - 作战/探索消耗资源
    ActionPoint_Value = 0  # 当前行动力数量
    ActionPoint_Total = 0  # 行动力总上限
    ActionPoint_Color = '^0000FF'  # 行动力数值显示颜色码
    ActionPoint_Record = datetime.datetime(2020, 1, 1, 0, 0)  # 行动力最后更新时间

    # 功勋配置 - 公会/任务奖励货币
    Merit_Value = 0  # 当前功勋数量
    Merit_Color = '^FFFF00'  # 功勋数值显示颜色码
    Merit_Record = datetime.datetime(2020, 1, 1, 0, 0)  # 功勋最后更新时间

    # 魔方配置 - 建造核心资源
    Cube_Value = 0  # 当前魔方数量
    Cube_Color = '^33FFFF'  # 魔方数值显示颜色码
    Cube_Record = datetime.datetime(2020, 1, 1, 0, 0)  # 魔方最后更新时间

    # 核心配置 - 改造/突破资源
    Core_Value = 0  # 当前核心数量
    Core_Color = '^AAAAAA'  # 核心数值显示颜色码
    Core_Record = datetime.datetime(2020, 1, 1, 0, 0)  # 核心最后更新时间

    # 勋章配置 - 成就/兑换货币
    Medal_Value = 0  # 当前勋章数量
    Medal_Color = '^FFDD00'  # 勋章数值显示颜色码
    Medal_Record = datetime.datetime(2020, 1, 1, 0, 0)  # 勋章最后更新时间

    # 公会币配置 - 公会商店兑换货币
    GuildCoin_Value = 0  # 当前公会币数量
    GuildCoin_Color = '^AAAAAA'  # 公会币数值显示颜色码
    GuildCoin_Record = datetime.datetime(2020, 1, 1, 0, 0)  # 公会币最后更新时间

    # ===================== 任务调度配置组 =====================
    Scheduler_Enable = False  # 是否启用任务调度（True/False）
    Scheduler_NextRun = datetime.datetime(2020, 1, 1, 0, 0)  # 下一次调度执行时间
    Scheduler_Command = 'Alas'  # 调度执行的命令/任务名称
    Scheduler_SuccessInterval = 0  # 任务执行成功后间隔时间（秒）
    Scheduler_FailureInterval = 120  # 任务执行失败后间隔时间（秒）
    Scheduler_ServerUpdate = '00:00'  # 服务器每日更新时间（用于校准调度）

    # ===================== 模拟器配置组 =====================
    Emulator_Serial = 'auto'  # 模拟器设备序列号（auto=自动识别）
    Emulator_PackageName = 'auto'  # 游戏包名（auto=自动识别，支持多服：国服/国际服/日服/台服等）
    # 可选值：auto, com.bilibili.azurlane, com.YoStarEN.AzurLane, com.YoStarJP.AzurLane, com.hkmanjuu.azurlane.gp等
    Emulator_ServerName = 'disabled'  # 游戏服务器名称（disabled=禁用，支持安卓/iOS多区服）
    # 可选值：disabled, cn_android-0~27, cn_ios-0~9, cn_channel-0~4, en-0~5, jp-0~17
    Emulator_ScreenshotMethod = 'auto'  # 截图方式（auto=自动选择，适配不同模拟器）
    # 可选值：auto, ADB, ADB_nc, uiautomator2, aScreenCap, aScreenCap_nc, DroidCast等
    Emulator_ControlMethod = 'MaaTouch'  # 操控方式（优先使用MaaTouch提升精度）
    # 可选值：ADB, uiautomator2, minitouch, Hermit, MaaTouch
    Emulator_ScreenshotDedithering = False  # 是否启用截图去抖动（提升识别精度）
    Emulator_AdbRestart = False  # 是否自动重启ADB（解决连接问题）

    # ===================== 模拟器信息配置组 =====================
    EmulatorInfo_Emulator = 'auto'  # 模拟器类型（auto=自动识别）
    # 可选值：auto, NoxPlayer, NoxPlayer64, BlueStacks4, BlueStacks5, LDPlayer3/4/9, MuMuPlayer等
    EmulatorInfo_name = None  # 模拟器名称（自动识别后填充）
    EmulatorInfo_path = None  # 模拟器安装路径（自动识别后填充）

    # ===================== 错误处理配置组 =====================
    Error_HandleError = True  # 是否自动处理错误（True=尝试恢复）
    Error_SaveError = True  # 是否保存错误截图/日志
    Error_StrictRestart = False  # 是否严格重启（遇到错误时强制重启游戏/模拟器）
    Error_OnePushConfig = 'provider: null'  # 错误推送配置（OnePush服务）
    Error_ScreenshotLength = 1  # 错误时保存截图数量

    # ===================== 性能优化配置组 =====================
    Optimization_ScreenshotInterval = 0.3  # 普通截图间隔（秒，平衡效率与性能）
    Optimization_CombatScreenshotInterval = 1.0  # 战斗中截图间隔（秒，减少性能消耗）
    Optimization_TaskHoardingDuration = 0  # 任务囤积执行时长（秒，批量处理提升效率）
    Optimization_WhenTaskQueueEmpty = 'goto_main'  # 任务队列为空时的行为
    # 可选值：stay_there(停留), goto_main(返回主界面), close_game(关闭游戏)

    # ===================== 掉落记录配置组 =====================
    DropRecord_SaveFolder = './screenshots'  # 掉落截图保存目录
    DropRecord_AzurStatsID = None  # AzurStats统计平台ID（用于上传掉落数据）
    DropRecord_API = 'default'  # 数据上传API（default=官方接口，cn_gz_reverse_proxy=国内反向代理）
    DropRecord_ResearchRecord = 'do_not'  # 科研记录方式
    # 可选值：do_not(不记录), save(本地保存), upload(仅上传), save_and_upload(保存并上传)
    DropRecord_CommissionRecord = 'do_not'  # 委托记录方式（同上）
    DropRecord_CombatRecord = 'do_not'  # 战斗掉落记录方式（同上）
    DropRecord_OpsiRecord = 'do_not'  # 作战档案记录方式（同上）
    DropRecord_MeowfficerBuy = 'do_not'  # 猫娘购买记录方式（同上）
    DropRecord_MeowfficerTalent = 'do_not'  # 猫娘天赋记录方式（同上）
    DropRecord_TelemetryReport = True  # 是否上传遥测数据（用于优化）
    DropRecord_BugReport = True  # 是否自动上报Bug

    # ===================== 退役配置组 =====================
    Retirement_RetireMode = 'one_click_retire'  # 退役模式
    # 可选值：one_click_retire(一键退役), enhance(强化退役), old_retire(旧版退役)

    # ===================== 任务优先级配置组 =====================
    YukikazeTaskManager_TaskPriorityAdjustment = '''Restart
> OpsiCrossMonth
> Commission > Tactical > Research
> Exercise
> Dorm > Meowfficer > Guild > Gacha
> Reward
> ShopFrequent > ShopOnce > Shipyard > Freebies
> PrivateQuarters
> OpsiExplore
> Minigame > Awaken
> OpsiAshBeacon
> OpsiDaily > OpsiShop > OpsiVoucher
> OpsiAbyssal > OpsiStronghold > OpsiObscure > OpsiArchive
> Daily > Hard > OpsiAshBeacon > OpsiAshAssist > OpsiMonthBoss
> Sos > EventSp > EventA > EventB > EventC > EventD
> RaidDaily > CoalitionSp > WarArchives > MaritimeEscort
> Event > Event2 > Raid > Hospital > HospitalEvent > Coalition > Main > Main2 > Main3
> OpsiMeowfficerFarming
> GemsFarming
> OpsiHazard1Leveling'''  # 任务优先级排序（从上到下优先级递减）

    # ===================== 一键退役配置组 =====================
    OneClickRetire_KeepLimitBreak = 'keep_limit_break'  # 是否保留突破舰船
    # 可选值：keep_limit_break(保留), do_not_keep(不保留)

    # ===================== 强化退役配置组 =====================
    Enhance_ShipToEnhance = 'all'  # 强化退役的舰船范围
    # 可选值：all(所有), favourite(仅收藏)
    Enhance_Filter = None  # 强化退役过滤条件（自定义）
    Enhance_CheckPerCategory = 5  # 每类舰船检查数量

    # ===================== 旧版退役配置组 =====================
    OldRetire_N = True  # 是否退役N级舰船
    OldRetire_R = True  # 是否退役R级舰船
    OldRetire_SR = False  # 是否退役SR级舰船
    OldRetire_SSR = False  # 是否退役SSR级舰船
    OldRetire_RetireAmount = 'retire_all'  # 退役数量
    # 可选值：retire_all(全部), retire_10(每次10艘)

    # ===================== 战役配置组 =====================
    Campaign_Name = '12-4'  # 战役关卡名称（如12-4、活动关卡）
    Campaign_Event = 'campaign_main'  # 战役类型（campaign_main=主线战役）
    Campaign_Mode = 'normal'  # 战役难度（normal=普通，hard=困难）
    Campaign_UseClearMode = True  # 是否启用清场模式
    Campaign_UseFleetLock = True  # 是否锁定舰队配置
    Campaign_UseAutoSearch = True  # 是否启用自动索敌
    Campaign_Use2xBook = False  # 是否使用2倍经验书
    Campaign_AmbushEvade = True  # 是否规避伏击

    # ===================== 停止条件配置组 =====================
    StopCondition_OilLimit = 1000  # 石油下限（低于该值停止战役）
    StopCondition_RunCount = 0  # 运行次数上限（0=无限制）
    StopCondition_MapAchievement = 'non_stop'  # 地图完成度停止条件
    # 可选值：non_stop(不停止), non_stop_clear_all(清完所有敌人), 100_percent_clear(100%探索)等
    StopCondition_StageIncrease = False  # 是否自动提升关卡
    StopCondition_GetNewShip = False  # 获得新舰船时是否停止
    StopCondition_ReachLevel = 0  # 等级达到指定值时停止（0=无限制）

    # ===================== 舰队配置组 =====================
    Fleet_Fleet1 = 1  # 第一舰队编号（1-6）
    Fleet_Fleet1Formation = 'double_line'  # 第一舰队阵型
    # 可选值：line_ahead(单纵), double_line(复纵), diamond(菱形)
    Fleet_Fleet1Mode = 'combat_auto'  # 第一舰队战斗模式
    # 可选值：combat_auto(自动战斗), combat_manual(手动战斗), stand_still_in_the_middle(中场停留)等
    Fleet_Fleet1Step = 3  # 第一舰队移动步数（2-5）
    Fleet_Fleet2 = 2  # 第二舰队编号（0=禁用，1-6）
    Fleet_Fleet2Formation = 'double_line'  # 第二舰队阵型（同上）
    Fleet_Fleet2Mode = 'combat_auto'  # 第二舰队战斗模式（同上）
    Fleet_Fleet2Step = 2  # 第二舰队移动步数（2-5）
    Fleet_FleetOrder = 'fleet1_mob_fleet2_boss'  # 舰队分工
    # 可选值：fleet1_mob_fleet2_boss(一队清杂二队打boss), fleet1_boss_fleet2_mob(一队打boss二队清杂)等

    # ===================== 潜艇配置组 =====================
    Submarine_Fleet = 0  # 潜艇所属舰队（0=禁用，1-2）
    Submarine_Mode = 'do_not_use'  # 潜艇使用模式
    # 可选值：do_not_use(禁用), hunt_only(仅狩猎), boss_only(仅打boss), hunt_and_boss(狩猎+boss)等
    Submarine_AutoSearchMode = 'sub_standby'  # 潜艇自动索敌模式
    # 可选值：sub_standby(待机), sub_auto_call(自动召唤)
    Submarine_DistanceToBoss = '2_grid_to_boss'  # 潜艇到boss的距离
    # 可选值：to_boss_position(直达boss), 1_grid_to_boss(距离boss1格), 2_grid_to_boss(距离boss2格)等

    # ===================== 心情配置组 =====================
    Emotion_Mode = 'calculate'  # 心情计算模式
    # 可选值：calculate(计算心情), ignore(忽略), calculate_ignore(计算但忽略惩罚)
    Emotion_Fleet1Value = 119  # 第一舰队当前心情值（0-200）
    Emotion_Fleet1Record = datetime.datetime(2020, 1, 1, 0, 0)  # 第一舰队心情最后更新时间
    Emotion_Fleet1Control = 'prevent_yellow_face'  # 第一舰队心情控制策略
    # 可选值：keep_exp_bonus(保持经验加成), prevent_green_face(防止绿脸), prevent_yellow_face(防止黄脸)等
    Emotion_Fleet1Recover = 'not_in_dormitory'  # 第一舰队心情恢复方式
    # 可选值：not_in_dormitory(不进宿舍), dormitory_floor_1(宿舍1楼), dormitory_floor_2(宿舍2楼)
    Emotion_Fleet1Oath = False  # 第一舰队是否婚舰（婚舰心情消耗降低）
    Emotion_Fleet1Onsen = False  # 第一舰队是否使用温泉（恢复心情）
    Emotion_Fleet2Value = 119  # 第二舰队当前心情值
    Emotion_Fleet2Record = datetime.datetime(2020, 1, 1, 0, 0)  # 第二舰队心情最后更新时间
    Emotion_Fleet2Control = 'prevent_yellow_face'  # 第二舰队心情控制策略（同上）
    Emotion_Fleet2Recover = 'not_in_dormitory'  # 第二舰队心情恢复方式（同上）
    Emotion_Fleet2Oath = False  # 第二舰队是否婚舰
    Emotion_Fleet2Onsen = False  # 第二舰队是否使用温泉

    # ===================== 血量控制配置组 =====================
    HpControl_UseHpBalance = False  # 是否启用血量平衡（调整舰队血量分布）
    HpControl_UseEmergencyRepair = False  # 是否使用紧急维修
    HpControl_UseLowHpRetreat = False  # 低血量时是否撤退
    HpControl_HpBalanceThreshold = 0.2  # 血量平衡阈值（0-1）
    HpControl_HpBalanceWeight = '1000, 1000, 1000'  # 血量平衡权重（前排/中排/后排）
    HpControl_RepairUseSingleThreshold = 0.3  # 单格维修阈值（0-1）
    HpControl_RepairUseMultiThreshold = 0.6  # 多格维修阈值（0-1）
    HpControl_LowHpRetreatThreshold = 0.3  # 低血量撤退阈值（0-1）

    # ===================== 敌人优先级配置组 =====================
    EnemyPriority_EnemyScaleBalanceWeight = 'default_mode'  # 敌人规模平衡权重
    # 可选值：default_mode(默认), S3_enemy_first(优先S3敌人), S1_enemy_first(优先S1敌人)

    # ===================== C11好感度刷取配置组 =====================
    C11AffinityFarming_RunCount = 32  # C11关卡运行次数（刷好感度）

    # ===================== C72神秘海域配置组 =====================
    C72MysteryFarming_StepOnA3 = True  # 是否踩A3格子（C72关卡特定策略）

    # ===================== C122中型练级配置组 =====================
    C122MediumLeveling_LargeEnemyTolerance = 1  # 大型敌人容忍数（0-10）

    # ===================== C124大型练级配置组 =====================
    C124LargeLeveling_NonLargeEnterTolerance = 1  # 非大型敌人进入容忍数（0-2）
    C124LargeLeveling_NonLargeRetreatTolerance = 1  # 非大型敌人撤退容忍数（0-10）
    C124LargeLeveling_PickupAmmo = 3  # 拾取弹药数量（3-5）

    # ===================== 钻石刷取配置组 =====================
    GemsFarming_ChangeFlagship = 'ship_equip'  # 更换旗舰方式
    # 可选值：ship(仅换船), ship_equip(换船+装备)
    GemsFarming_CommonCV = 'any'  # 常用航母选择
    # 可选值：custom(自定义), any(任意), eagle(鹰), langley(兰利), bogue(博格)等
    GemsFarming_CommonCVFilter = 'bogue > ranger > langley > hermes'  # 航母筛选优先级
    GemsFarming_ChangeVanguard = 'ship_equip'  # 更换先锋方式
    # 可选值：disabled(禁用), ship(仅换船), ship_equip(换船+装备)
    GemsFarming_CommonDD = 'any'  # 常用驱逐舰选择
    # 可选值：custom(自定义), any(任意), favourite(收藏), aulick_or_foote(奥利克/福特)等
    GemsFarming_CommonDDFilter = 'z20 > z21 > aulick > foote > cassin > downes'  # 驱逐舰筛选优先级
    GemsFarming_EquipmentCode = '''DD: null
bogue: null
hermes: null
langley: null
ranger: null'''  # 各舰船装备配置
    GemsFarming_ALLowHighFlagshipLevel = False  # 是否允许高等级旗舰
    GemsFarming_ALLowLowVanguardLevel = False  # 是否允许低等级先锋
    GemsFarming_DelayTaskIFNoFlagship = False  # 无旗舰时是否延迟任务
    GemsFarming_CommissionLimit = False  # 是否限制委托

    # ===================== 活动通用配置组 =====================
    EventGeneral_PtLimit = 0  # 活动PT上限（0=无限制）
    EventGeneral_TimeLimit = datetime.datetime(2020, 1, 1, 0, 0)  # 活动时间限制

    # ===================== 任务平衡配置组 =====================
    TaskBalancer_Enable = False  # 是否启用任务平衡
    TaskBalancer_CoinLimit = 10000  # 金币平衡上限
    TaskBalancer_TaskCall = 'Main'  # 任务调用类型（Main/Main2/Main3）

    # ===================== 活动日常配置组 =====================
    EventDaily_StageFilter = 'A1 > A2 > A3'  # 活动日常关卡筛选优先级
    EventDaily_LastStage = 0  # 最后执行的关卡

    # ===================== 突袭配置组 =====================
    Raid_Mode = 'hard'  # 突袭难度（easy/normal/hard/ex）
    Raid_UseTicket = False  # 是否使用突袭票

    # ===================== 突袭日常配置组 =====================
    RaidDaily_StageFilter = 'hard > normal > easy'  # 突袭日常关卡筛选优先级

    # ===================== 医院配置组 =====================
    Hospital_UseRecommendFleet = True  # 是否使用推荐舰队

    # ===================== 医院活动配置组 =====================
    HospitalEvent_Mode = 'hard'  # 医院活动难度（easy/normal/hard）
    HospitalEvent_Stage = 'T1'  # 医院活动关卡（T1-T4/ESP）

    # ===================== 护航配置组 =====================
    MaritimeEscort_Enable = True  # 是否启用护航任务

    # ===================== 联合作战配置组 =====================
    Coalition_Mode = 'area1-normal'  # 联合作战模式（area1-6，normal/hard）
    Coalition_Fleet = 'single'  # 舰队数量（single=单舰队，multi=多舰队）

    # ===================== 活动商店配置组 =====================
    EventShop_UnlockSSRShip = True  # 是否解锁SSR舰船
    EventShop_BuyURShip = 2  # UR舰船购买数量（0-2）
    EventShop_PresetFilter = 'all'  # 预设筛选规则（all/custom）
    EventShop_CustomFilter = '''EquipUR > EquipSSR > Cube > GachaTicket
> Array > Chip > CatT3 
> Meta > SkinBox
> Oil > Coin > Medal > ExpBookT1 > FoodT1
> DR > PR
> AugmentCore > AugmentEnhanceT2 > AugmentChangeT2 > AugmentChangeT1
> CatT2 > CatT1 > PlateGeneralT3 > PlateT3 > BoxT4
> ShipSSR'''  # 自定义商店兑换优先级

    # ===================== 委托配置组 =====================
    Commission_PresetFilter = 'cube'  # 委托预设筛选（cube/chip/oil/custom等）
    Commission_CustomFilter = '''DailyEvent > Gem-4 > Gem-2 > Gem-8 > ExtraCube-0:30
> UrgentCube-1:30 > UrgentCube-1:45 > UrgentCube-3
> ExtraDrill-5:20 > ExtraDrill-2 > ExtraDrill-3:20
> UrgentCube-2:15 > UrgentCube-4
> ExtraDrill-1 > UrgentCube-6 > ExtraCube-1:30
> ExtraDrill-2:40 > ExtraDrill-0:20
> Major > DailyChip > DailyResource
> ExtraPart-0:30 > ExtraOil-1 > UrgentBox-6
> ExtraCube-3 > ExtraPart-1 > UrgentBox-3
> ExtraCube-4 > ExtraPart-1:30 > ExtraOil-4
> UrgentBox-1 > ExtraCube-5 > UrgentBox-1
> ExtraCube-8 > ExtraOil-8
> UrgentDrill-4 > UrgentDrill-2:40 > UrgentDrill-2
> UrgentDrill-1 > UrgentDrill-1:30 > UrgentDrill-1:10
> Extra-0:20 > Extra-0:30 > Extra-1:00 > Extra-1:30 > Extra-2:00
> shortest'''  # 自定义委托筛选优先级
    Commission_DoMajorCommission = False  # 是否执行大型委托

    # ===================== 战术学院配置组 =====================
    Tactical_TacticalFilter = '''SameT4 > SameT3 > SameT2 > SameT1
> BlueT2 > YellowT2 > RedT2
> BlueT3 > YellowT3 > RedT3
> BlueT4 > YellowT4 > RedT4
> BlueT1 > YellowT1 > RedT1
> first'''  # 战术学院筛选优先级
    Tactical_RapidTrainingSlot = 'do_not_use'  # 快速训练槽位（do_not_use/slot_1-4）

    # ===================== 经验溢出控制配置组 =====================
    ControlExpOverflow_Enable = True  # 是否启用经验溢出控制
    ControlExpOverflow_T4Allow = 100  # T4舰船经验溢出允许值
    ControlExpOverflow_T3Allow = 100  # T3舰船经验溢出允许值
    ControlExpOverflow_T2Allow = 200  # T2舰船经验溢出允许值
    ControlExpOverflow_T1Allow = 200  # T1舰船经验溢出允许值

    # ===================== 新增学员配置组 =====================
    AddNewStudent_Enable = False  # 是否添加新学员
    AddNewStudent_Favorite = True  # 是否收藏新学员

    # ===================== 科研配置组 =====================
    Research_UseCube = 'only_05_hour'  # 魔方使用策略
    # 可选值：always_use(总是使用), only_05_hour(仅0.5小时项目), only_no_project(仅无项目时), do_not_use(不使用)
    Research_UseCoin = 'always_use'  # 金币使用策略（同上）
    Research_UsePart = 'always_use'  # 部件使用策略（同上）
    Research_AllowDelay = True  # 是否允许延迟科研
    Research_PresetFilter = 'series_8_blueprint_305'  # 科研预设筛选（自定义/各系列蓝图）
    Research_CustomFilter = '''S8-DR0.5 > S8-PRY0.5 > S8-Q0.5 > S8-H0.5 > Q0.5 > S8-DR2.5
> S8-G1.5 > S8-Q1 > S8-DR5 > 0.5 > S8-G4 > S8-Q2 > S8-PRY2.5 > reset
> S8-DR8 > Q1 > 1 > S8-E-315 > S8-G2.5 > G1.5 > 1.5 > S8-E-031
> S8-Q4 > Q2 > E2 > 2 > DR2.5 > PRY2.5 > G2.5 > 2.5 > S8-PRY5
> S8-PRY8 > Q4 > G4 > 4 > S8-C6 > DR5 > PRY5 > 5 > C6 > 6 > S8-C8
> S8-C12 > DR8 > PRY8 > C8 > 8 > C12 > 12'''  # 自定义科研优先级

    # ===================== 宿舍配置组 =====================
    Dorm_Collect = True  # 是否收取宿舍收益
    Dorm_Feed = True  # 是否投喂宿舍角色
    Dorm_FeedFilter = '20000 > 10000 > 5000 > 3000 > 2000 > 1000'  # 投喂优先级（按好感度）

    # ===================== 购买家具配置组 =====================
    BuyFurniture_Enable = False  # 是否购买家具
    BuyFurniture_BuyOption = 'all'  # 购买选项（set/all）
    BuyFurniture_LastRun = datetime.datetime(2020, 1, 1, 0, 0)  # 最后购买时间

    # ===================== 猫娘配置组 =====================
    Meowfficer_BuyAmount = 1  # 猫娘购买数量
    Meowfficer_FortChoreMeowfficer = True  # 是否派遣猫娘执行要塞任务

    # ===================== 猫娘训练配置组 =====================
    MeowfficerTrain_Enable = False  # 是否启用猫娘训练
    MeowfficerTrain_Mode = 'seamlessly'  # 训练模式（seamlessly/once_a_day）
    MeowfficerTrain_RetainTalentedGold = True  # 是否保留金色天赋猫娘
    MeowfficerTrain_RetainTalentedPurple = True  # 是否保留紫色天赋猫娘
    MeowfficerTrain_EnhanceIndex = 1  # 强化索引
    MeowfficerTrain_MaxFeedLevel = 5  # 最大投喂等级

    # ===================== 公会后勤配置组 =====================
    GuildLogistics_Enable = True  # 是否启用公会后勤
    GuildLogistics_SelectNewMission = False  # 是否选择新任务
    GuildLogistics_ExchangeFilter = '''PlateTorpedoT1 > PlateAntiAirT1 > PlatePlaneT1 > PlateGunT1 > PlateGeneralT1
> PlateTorpedoT2 > PlateAntiAirT2 > PlatePlaneT2 > PlateGunT2 > PlateGeneralT2
> PlateTorpedoT3 > PlateAntiAirT3 > PlatePlaneT3 > PlateGunT3 > PlateGeneralT3
> OxyCola > Coolant > Merit > Coin > Oil'''  # 公会后勤兑换优先级

    # ===================== 公会行动配置组 =====================
    GuildOperation_Enable = True  # 是否启用公会行动
    GuildOperation_SelectNewOperation = False  # 是否选择新行动
    GuildOperation_NewOperationMaxDate = 15  # 新行动最大天数
    GuildOperation_JoinThreshold = 1  # 加入阈值
    GuildOperation_AttackBoss = True  # 是否攻击boss
    GuildOperation_BossFleetRecommend = False  # 是否使用推荐boss舰队

    # ===================== 奖励配置组 =====================
    Reward_CollectOil = True  # 是否收取石油奖励
    Reward_CollectCoin = True  # 是否收取金币奖励
    Reward_CollectExp = True  # 是否收取经验奖励
    Reward_CollectMission = True  # 是否收取任务奖励
    Reward_CollectWeeklyMission = False  # 是否收取周任务奖励

    # ===================== 觉醒配置组 =====================
    Awaken_LevelCap = 'level120'  # 觉醒等级上限（level120/level125）
    Awaken_Favourite = False  # 是否仅觉醒收藏舰船

    # ===================== 岛1配置组（角色互动） =====================
    Island1_Receive = False  # 是否收取奖励
    Island1_Option1 = 0  # 选项1（0-8）
    Island1_Character1 = 'manjuu'  # 角色1（manjuu/萨拉托加/新泽西等）
    Island1_Option2 = 0  # 选项2（0-8）
    Island1_Character2 = 'manjuu'  # 角色2（同上）
    Island1_Option3 = 0  # 选项3（0-8）
    Island1_Character3 = 'manjuu'  # 角色3（同上）
    Island1_Option4 = 0  # 选项4（0-8）
    Island1_Character4 = 'manjuu'  # 角色4（同上）

    # ===================== 岛2配置组（角色互动） =====================
    Island2_Receive = False  # 是否收取奖励
    Island2_Option1 = 0  # 选项1（0-1）
    Island2_Character1 = 'manjuu'  # 角色1（同上）
    Island2_Option2 = 0  # 选项2（0-2）
    Island2_Character2 = 'manjuu'  # 角色2（同上）
    Island2_Option3 = 0  # 选项3（0-3）
    Island2_Character3 = 'manjuu'  # 角色3（同上）
    Island2_Option4 = 0  # 选项4（0-4）
    Island2_Character4 = 'manjuu'  # 角色4（同上）

    # ===================== 岛3配置组（角色互动） =====================
    Island3_Receive = False  # 是否收取奖励
    Island3_Option1 = 0  # 选项1（0-6）
    Island3_Character1 = 'manjuu'  # 角色1（同上）
    Island3_Option2 = 0  # 选项2（0-6）
    Island3_Character2 = 'manjuu'  # 角色2（同上）
    Island3_Option3 = 0  # 选项3（0-6）
    Island3_Character3 = 'manjuu'  # 角色3（同上）
    Island3_Option4 = 0  # 选项4（0-6）
    Island3_Character4 = 'manjuu'  # 角色4（同上）

    # ===================== 岛4配置组（角色互动） =====================
    Island4_Receive = False  # 是否收取奖励
    Island4_Option1 = 0  # 选项1（0-4）
    Island4_Character1 = 'manjuu'  # 角色1（同上）
    Island4_Option2 = 0  # 选项2（0-4）
    Island4_Character2 = 'manjuu'  # 角色2（同上）
    Island4_Option3 = 0  # 选项3（0-4）
    Island4_Character3 = 'manjuu'  # 角色3（同上）
    Island4_Option4 = 0  # 选项4（0-4）
    Island4_Character4 = 'manjuu'  # 角色4（同上）

    # ===================== 岛5配置组（角色互动） =====================
    Island5_Receive = False  # 是否收取奖励
    Island5_Option1 = 0  # 选项1（0-9）
    Island5_Character1 = 'manjuu'  # 角色1（同上）
    Island5_Option2 = 0  # 选项2（0-9）
    Island5_Character2 = 'manjuu'  # 角色2（同上）
    Island5_Option3 = 0  # 选项3（0-9）
    Island5_Character3 = 'manjuu'  # 角色3（同上）
    Island5_Option4 = 0  # 选项4（0-9）
    Island5_Character4 = 'manjuu'  # 角色4（同上）

    # ===================== 岛6配置组（角色互动） =====================
    Island6_Receive = False  # 是否收取奖励
    Island6_Option1 = 0  # 选项1（0-7）
    Island6_Character1 = 'manjuu'  # 角色1（同上）
    Island6_Option2 = 0  # 选项2（0-7）
    Island6_Character2 = 'manjuu'  # 角色2（同上）

    # ===================== 岛7配置组（角色互动） =====================
    Island7_Receive = False  # 是否收取奖励
    Island7_Option1 = 0  # 选项1（0-9）
    Island7_Character1 = 'manjuu'  # 角色1（同上）
    Island7_Option2 = 0  # 选项2（0-9）
    Island7_Character2 = 'manjuu'  # 角色2（同上）

    # ===================== 岛8配置组（角色互动） =====================
    Island8_Receive = False  # 是否收取奖励
    Island8_Option1 = 0  # 选项1（0-11）
    Island8_Character1 = 'manjuu'  # 角色1（同上）
    Island8_Option2 = 0  # 选项2（0-11）
    Island8_Character2 = 'manjuu'  # 角色2（同上）

    # ===================== 岛9配置组（角色互动） =====================
    Island9_Receive = False  # 是否收取奖励
    Island9_Option1 = 0  # 选项1（0-9）
    Island9_Character1 = 'manjuu'  # 角色1（同上）
    Island9_Option2 = 0  # 选项2（0-9）
    Island9_Character2 = 'manjuu'  # 角色2（同上）

    # ===================== 岛10配置组（角色互动） =====================
    Island10_Receive = False  # 是否收取奖励
    Island10_Option1 = 0  # 选项1（0-7）
    Island10_Character1 = 'manjuu'  # 角色1（同上）
    Island10_Option2 = 0  # 选项2（0-7）
    Island10_Character2 = 'manjuu'  # 角色2（同上）

    # ===================== 岛11配置组（角色互动） =====================
    Island11_Receive = False  # 是否收取奖励
    Island11_Option1 = 0  # 选项1（0-5）
    Island11_Character1 = 'manjuu'  # 角色1（同上）
    Island11_Option2 = 0  # 选项2（0-5）
    Island11_Character2 = 'manjuu'  # 角色2（同上）

    # ===================== 岛12配置组（角色互动） =====================
    Island12_Receive = False  # 是否收取奖励
    Island12_Option1 = 0  # 选项1（0-6）
    Island12_Character1 = 'manjuu'  # 角色1（同上）
    Island12_Option2 = 0  # 选项2（0-6）
    Island12_Character2 = 'manjuu'  # 角色2（同上）

    # ===================== 岛13配置组（角色互动） =====================
    Island13_Receive = False  # 是否收取奖励
    Island13_Option1 = 0  # 选项1（0-4）
    Island13_Character1 = 'manjuu'  # 角色1（同上）
    Island13_Option2 = 0  # 选项2（0-4）
    Island13_Character2 = 'manjuu'  # 角色2（同上）

    # ===================== 岛14配置组（角色互动） =====================
    Island14_Receive = False  # 是否收取奖励
    Island14_Option1 = 0  # 选项1（0-9）
    Island14_Character1 = 'manjuu'  # 角色1（同上）
    Island14_Option2 = 0  # 选项2（0-9）
    Island14_Character2 = 'manjuu'  # 角色2（同上）

    # ===================== 岛15配置组（角色互动） =====================
    Island15_Receive = False  # 是否收取奖励
    Island15_Option1 = 0  # 选项1（0-9）
    Island15_Character1 = 'manjuu'  # 角色1（同上）
    Island15_Option2 = 0  # 选项2（0-9）
    Island15_Character2 = 'manjuu'  # 角色2（同上）

    # ===================== 通用商店配置组 =====================
    GeneralShop_UseGems = False  # 是否使用钻石购买
    GeneralShop_Refresh = False  # 是否刷新商店
    GeneralShop_BuySkinBox = False  # 是否购买皮肤箱
    GeneralShop_ConsumeCoins = False  # 是否消耗金币
    GeneralShop_Filter = 'BookRedT3 > BookYellowT3 > BookBlueT3 > BookRedT2 > Cube > FoodT6 > FoodT5'  # 商店兑换优先级

    # ===================== 公会商店配置组 =====================
    GuildShop_Refresh = True  # 是否刷新公会商店
    GuildShop_Filter = 'PlateT4 > BookT3 > PR > CatT3 > Chip > BookT2 > Retrofit > FoodT6 > FoodT5 > CatT2 > BoxT4'  # 兑换优先级
    GuildShop_BOX_T3 = 'ironblood'  # T3箱子类型（eagle/royal/sakura/ironblood）
    GuildShop_BOX_T4 = 'ironblood'  # T4箱子类型（同上）
    GuildShop_BOOK_T2 = 'red'  # T2书籍类型（red/blue/yellow）
    GuildShop_BOOK_T3 = 'red'  # T3书籍类型（同上）
    GuildShop_RETROFIT_T2 = 'cl'  # T2改造类型（dd/cl/bb/cv）
    GuildShop_RETROFIT_T3 = 'cl'  # T3改造类型（同上）
    GuildShop_PLATE_T2 = 'general'  # T2钢板类型（general/gun/torpedo/antiair/plane）
    GuildShop_PLATE_T3 = 'general'  # T3钢板类型（同上）
    GuildShop_PLATE_T4 = 'gun'  # T4钢板类型（同上）
    GuildShop_PR1 = 'neptune'  # PR1舰船（neptune/monarch/ibuki等）
    GuildShop_PR2 = 'seattle'  # PR2舰船（seattle/georgia/kitakaze等）
    GuildShop_PR3 = 'cheshire'  # PR3舰船（cheshire/mainz/odin等）

    # ===================== 勋章商店2配置组 =====================
    MedalShop2_Filter = '''DR > PR
> BookRedT3 > BookYellowT3 > BookBlueT3
> BookRedT2 > BookYellowT2 > BookBlueT2
> RetrofitT3
> FoodT6 > FoodT5
> PlateGeneralT3 > PlateWildT3'''  # 勋章商店兑换优先级
    MedalShop2_RETROFIT_T1 = 'cl'  # T1改造类型（dd/cl/bb/cv）
    MedalShop2_RETROFIT_T2 = 'cl'  # T2改造类型（同上）
    MedalShop2_RETROFIT_T3 = 'cl'  # T3改造类型（同上）
    MedalShop2_PLATE_T1 = 'general'  # T1钢板类型（general/gun/torpedo/antiair/plane）
    MedalShop2_PLATE_T2 = 'general'  # T2钢板类型（同上）
    MedalShop2_PLATE_T3 = 'general'  # T3钢板类型（同上）

    # ===================== 功勋商店配置组 =====================
    MeritShop_Refresh = False  # 是否刷新功勋商店
    MeritShop_Filter = 'Cube'  # 功勋商店兑换优先级

    # ===================== 核心商店配置组 =====================
    CoreShop_Filter = 'Array'  # 核心商店兑换优先级

    # ===================== 造船厂DR配置组 =====================
    ShipyardDr_ResearchSeries = 2  # 科研系列（2-4）
    ShipyardDr_ShipIndex = 0  # 舰船索引（0-6）
    ShipyardDr_BuyAmount = 2  # 购买数量
    ShipyardDr_LastRun = datetime.datetime(2020, 1, 1, 0, 0)  # 最后运行时间

    # ===================== 造船厂配置组 =====================
    Shipyard_ResearchSeries = 1  # 科研系列（1-5）
    Shipyard_ShipIndex = 0  # 舰船索引（0-6）
    Shipyard_BuyAmount = 2  # 购买数量
    Shipyard_LastRun = datetime.datetime(2020, 1, 1, 0, 0)  # 最后运行时间

    # ===================== 抽卡配置组 =====================
    Gacha_Pool = 'light'  # 卡池类型（light/heavy/special/event/wishing_well）
    Gacha_Amount = 1  # 抽卡数量（1-10）
    Gacha_UseTicket = True  # 是否使用抽卡券
    Gacha_UseDrill = False  # 是否使用钻井

    # ===================== 战令配置组 =====================
    BattlePass_Collect = True  # 是否收取战令奖励

    # ===================== 数据密钥配置组 =====================
    DataKey_Collect = True  # 是否收取数据密钥
    DataKey_ForceCollect = False  # 是否强制收取

    # ===================== 邮件配置组 =====================
    Mail_ClaimMerit = True  # 是否收取功勋邮件
    Mail_ClaimMaintenance = False  # 是否收取维护补偿邮件
    Mail_ClaimTradeLicense = False  # 是否收取贸易许可证邮件
    Mail_DeleteCollected = True  # 是否删除已收取的邮件

    # ===================== 补给包配置组 =====================
    SupplyPack_Collect = True  # 是否收取补给包
    SupplyPack_DayOfWeek = 0  # 星期几收取（0-6，0=周日）

    # ===================== 小游戏配置组 =====================
    Minigame_Collect = False  # 是否收取小游戏奖励

    # ===================== 私人宿舍配置组 =====================
    PrivateQuarters_BuyRoses = True  # 是否购买玫瑰
    PrivateQuarters_BuyCake = False  # 是否购买蛋糕
    PrivateQuarters_TargetInteract = True  # 是否与目标角色互动
    PrivateQuarters_TargetShip = 'anchorage'  # 目标角色（anchorage/noshiro/sirius等）

    # ===================== 日常配置组 =====================
    Daily_UseDailySkip = True  # 是否使用日常跳过券
    Daily_EscortMission = 'first'  # 护航任务（skip/first/second/third）
    Daily_EscortMissionFleet = 1  # 护航任务舰队（1-6）
    Daily_AdvanceMission = 'first'  # 进阶任务（skip/first/second/third）
    Daily_AdvanceMissionFleet = 1  # 进阶任务舰队（1-6）
    Daily_FierceAssault = 'first'  # 强袭任务（skip/first/second/third）
    Daily_FierceAssaultFleet = 1  # 强袭任务舰队（1-6）
    Daily_TacticalTraining = 'second'  # 战术训练（skip/first/second/third）
    Daily_TacticalTrainingFleet = 1  # 战术训练舰队（1-6）
    Daily_SupplyLineDisruption = 'second'  # 补给线切断（skip/first/second/third）
    Daily_ModuleDevelopment = 'first'  # 模块研发（skip/first/second）
    Daily_ModuleDevelopmentFleet = 1  # 模块研发舰队（1-6）
    Daily_EmergencyModuleDevelopment = 'first'  # 紧急模块研发（skip/first/second）
    Daily_EmergencyModuleDevelopmentFleet = 1  # 紧急模块研发舰队（1-6）

    # ===================== 困难关卡配置组 =====================
    Hard_HardStage = '11-4'  # 困难关卡名称
    Hard_HardFleet = 1  # 困难关卡舰队（1-2）

    # ===================== 演习配置组 =====================
    Exercise_DelayUntilHoursBeforeNextUpdate = 12  # 演习延迟执行时间（1-12小时）
    Exercise_OpponentChooseMode = 'max_exp'  # 对手选择模式（max_exp/easiest/leftmost等）
    Exercise_OpponentTrial = 1  # 对手尝试次数
    Exercise_ExerciseStrategy = 'aggressive'  # 演习策略（aggressive/fri18/sat0等）
    Exercise_LowHpThreshold = 0.4  # 低血量阈值（0-1）
    Exercise_LowHpConfirmWait = 0.1  # 低血量确认等待时间（秒）
    Exercise_OpponentRefreshValue = 0  # 对手刷新阈值
    Exercise_OpponentRefreshRecord = datetime.datetime(2020, 1, 1, 0, 0)  # 对手最后刷新时间

    # ===================== 求救信号配置组 =====================
    Sos_Chapter = 3  # 求救信号章节（3-10）

    # ===================== 作战档案灰烬协助配置组 =====================
    OpsiAshAssist_Tier = 15  # 灰烬协助等级

    # ===================== 作战档案通用配置组 =====================
    OpsiGeneral_UseLogger = True  # 是否启用日志记录
    OpsiGeneral_BuyActionPointLimit = 0  # 行动力购买上限（0-5）
    OpsiGeneral_OilLimit = 1000  # 石油上限
    OpsiGeneral_RepairThreshold = 0.4  # 维修阈值（0-1）
    OpsiGeneral_UseRepairPack = False  # 是否使用维修包
    OpsiGeneral_RepairPackThreshold = 0.9  # 维修包使用阈值（0-1）
    OpsiGeneral_DoRandomMapEvent = True  # 是否执行随机地图事件
    OpsiGeneral_AkashiShopFilter = 'ActionPoint'  # 明石商店筛选
    OpsiGeneral_NotifyOpsiMail = True  # 是否通知作战档案邮件

    # ===================== 作战档案灰烬信标配置组 =====================
    OpsiAshBeacon_AttackMode = 'current'  # 攻击模式（current/current_dossier）
    OpsiAshBeacon_OneHitMode = True  # 是否一击模式
    OpsiAshBeacon_DossierAutoAttackMode = False  # 是否档案自动攻击模式
    OpsiAshBeacon_RequestAssist = True  # 是否请求协助
    OpsiAshBeacon_EnsureFullyCollected = True  # 是否确保完全收集
    OpsiAshBeacon_AutoCollectShip = True  # 是否自动收集舰船

    # ===================== 作战档案舰队筛选配置组 =====================
    OpsiFleetFilter_Filter = 'Fleet-4 > CallSubmarine > Fleet-2 > Fleet-3 > Fleet-1'  # 舰队筛选优先级

    # ===================== 作战档案舰队配置组 =====================
    OpsiFleet_Fleet = 1  # 舰队编号（1-4）
    OpsiFleet_Submarine = False  # 是否使用潜艇

    # ===================== 作战档案探索配置组 =====================
    OpsiExplore_SpecialRadar = False  # 是否使用特殊雷达
    OpsiExplore_ForceRun = False  # 是否强制运行
    OpsiExplore_IfSkipSirenResearch = 0  # 是否跳过塞壬科研（0/6/65/654）
    OpsiExplore_SkipedSirenResearch = None  # 已跳过的塞壬科研
    OpsiExplore_LastZone = 0  # 最后探索区域

    # ===================== 作战档案商店配置组 =====================
    OpsiShop_PresetFilter = 'max_benefit_meta'  # 预设筛选（max_benefit/max_benefit_meta等）
    OpsiShop_CustomFilter = '''LoggerAbyssalT6 > LoggerAbyssalT5 > LoggerObscure > LoggerAbyssalT4 > ActionPoint > PurpleCoins
> GearDesignPlanT3 > PlateRandomT4 > DevelopmentMaterialT3 > GearDesignPlanT2 > GearPart
> OrdnanceTestingReportT3 > OrdnanceTestingReportT2 > DevelopmentMaterialT2 > OrdnanceTestingReportT1
> METARedBook > CrystallizedHeatResistantSteel > NanoceramicAlloy > NeuroplasticProstheticArm > SupercavitationGenerator'''  # 自定义筛选
    OpsiShop_DisableBeforeDate = 0  # 禁用日期

    # ===================== 作战档案凭证配置组 =====================
    OpsiVoucher_Filter = 'LoggerAbyssal > LoggerObscure > Book > Coin > Fragment'  # 凭证兑换优先级

    # ===================== 作战档案日常配置组 =====================
    OpsiDaily_DoMission = True  # 是否执行日常任务
    OpsiDaily_UseTuningSample = True  # 是否使用调谐样本
    OpsiDaily_SkipSirenResearchMission = False  # 是否跳过塞壬科研任务
    OpsiDaily_KeepMissionZone = False  # 是否保留任务区域
    OpsiDaily_MissionZones = None  # 任务区域

    # ===================== 作战档案晦冥配置组 =====================
    OpsiObscure_SkipHazard2Obscure = False  # 是否跳过危险等级2的晦冥
    OpsiObscure_ForceRun = False  # 是否强制运行

    # ===================== 作战档案深渊配置组 =====================
    OpsiAbyssal_ForceRun = False  # 是否强制运行

    # ===================== 作战档案据点配置组 =====================
    OpsiStronghold_SubmarineEveryCombat = False  # 是否每次战斗都使用潜艇
    OpsiStronghold_ForceRun = False  # 是否强制运行
    OpsiStronghold_HasStronghold = True  # 是否有据点

    # ===================== 作战档案月度BOSS配置组 =====================
    OpsiMonthBoss_Mode = 'normal'  # 月度BOSS模式（normal/normal_hard）
    OpsiMonthBoss_CheckAdaptability = True  # 是否检查适应性
    OpsiMonthBoss_ForceRun = False  # 是否强制运行

    # ===================== 作战档案猫娘刷取配置组 =====================
    OpsiMeowfficerFarming_ActionPointPreserve = 1000  # 行动力保留值
    OpsiMeowfficerFarming_HazardLevel = 5  # 危险等级（2-10）
    OpsiMeowfficerFarming_TargetZone = 0  # 目标区域
    OpsiMeowfficerFarming_StayInZone = False  # 是否停留在区域
    OpsiMeowfficerFarming_APPreserveUntilReset = False  # 是否保留行动力直到重置

    # ===================== 作战档案危险1练级配置组 =====================
    OpsiHazard1Leveling_TargetZone = 0  # 目标区域（0/44/22）
    OpsiHazard1Leveling_OperationCoinsPreserve = 100000  # 运营币保留值
    OpsiHazard1Leveling_MinimumActionPointReserve = 200  # 最小行动力保留值
    OpsiHazard1Leveling_ExecuteFixedPatrolScan = False  # 是否执行固定巡逻扫描
    OpsiHazard1Leveling_Cl1Filter = 'ActionPoint'  # CL1筛选

    # ===================== 作战档案塞壬BUG配置组 =====================
    OpsiSirenBug_SirenResearch_Enable = False  # 是否启用塞壬科研
    OpsiSirenBug_SirenBug_Enable = False  # 是否启用塞壬BUG
    OpsiSirenBug_SirenBug_Type = 'dangerous'  # BUG类型（dangerous/safe）
    OpsiSirenBug_SirenBug_Zone = 0  # BUG区域
    OpsiSirenBug_DisableTaskSwitchDuringBug = False  # BUG期间是否禁用任务切换
    OpsiSirenBug_SirenBug_DailyCount = 0  # 每日BUG次数
    OpsiSirenBug_SirenBug_DailyCountRecord = datetime.datetime(2020, 1, 1, 0, 0)  # 每日BUG次数记录时间

    # ===================== 作战档案练级检查配置组 =====================
    OpsiCheckLeveling_TargetLevel = 0  # 目标等级
    OpsiCheckLeveling_LastRun = datetime.datetime(2020, 1, 2, 1, 0, 0)  # 最后运行时间
    OpsiCheckLeveling_DelayAfterFull = False  # 满级后是否延迟

    # ===================== 作战档案调度配置组 =====================
    OpsiScheduling_EnableSmartScheduling = False  # 是否启用智能调度
    OpsiScheduling_ActionPointNotifyLevels = '500,1000,2000,3000'  # 行动力通知阈值

    # ===================== 守护配置组 =====================
    Daemon_EnterMap = True  # 是否进入地图

    # ===================== 作战档案守护配置组 =====================
    OpsiDaemon_RepairShip = True  # 是否维修舰船
    OpsiDaemon_SelectEnemy = True  # 是否选择敌人

    # ===================== 活动剧情配置组 =====================
    EventStory_SkipBattle = False  # 是否跳过战斗（True/False）

    # ===================== 箱子拆解配置组 =====================
    BoxDisassemble_UsePurpleBox = False  # 是否使用紫箱
    BoxDisassemble_PurpleBoxLimit = 100  # 紫箱上限
    BoxDisassemble_UseBlueBox = False  # 是否使用蓝箱
    BoxDisassemble_BlueBoxLimit = 1000  # 蓝箱上限
    BoxDisassemble_UseWhiteBox = True  # 是否使用白箱
    BoxDisassemble_WhiteBoxLimit = 2000  # 白箱上限

    # ===================== 基准测试配置组 =====================
    Benchmark_DeviceType = 'emulator'  # 设备类型（emulator/phone_cloud_with_adb等）
    Benchmark_TestScene = 'screenshot_click'  # 测试场景（screenshot_click/screenshot/click）

    # ===================== 碧蓝航线反和谐配置组 =====================
    AzurLaneUncensored_Repository = 'https://gitee.com/LmeSzinc/AzurLaneUncensored'  # 反和谐仓库地址

    # ===================== 游戏管理配置组 =====================
    GameManager_AutoRestart = True  # 是否自动重启游戏

    # ===================== 存储配置组 =====================
    Storage_Storage = {}  # 通用存储字典（动态数据）